In [28]:
pip install python-dotenv

  Using cached python_dotenv-1.1.1-py3-none-any.whl.metadata (24 kB)
Using cached python_dotenv-1.1.1-py3-none-any.whl (20 kB)
Note: you may need to restart the kernel to use updated packages.


In [29]:
from dotenv import load_dotenv
import os

load_dotenv()

True

In [1]:
pip install faiss-cpu

  Using cached numpy-2.3.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
   ---------------------------------------- 0.0/18.2 MB ? eta -:--:--
   ------ --------------------------------- 2.9/18.2 MB 23.8 MB/s eta 0:00:01
   --------- ------------------------------ 4.2/18.2 MB 12.0 MB/s eta 0:00:02
   -------------- ------------------------- 6.6/18.2 MB 11.5 MB/s eta 0:00:02
   --------------------- ------------------ 9.7/18.2 MB 12.6 MB/s eta 0:00:01
   ------------------------ --------------- 11.3/18.2 MB 11.4 MB/s eta 0:00:01
   ------------------------------ --------- 13.9/18.2 MB 11.6 MB/s eta 0:00:01
   ------------------------------------ --- 16.8/18.2 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  18.1/18.2 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  18.1/18.2 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 18.2/18.2 MB 9.6 MB/s  0:00:01
Using cached numpy-2.3.2-cp312-cp312-win_amd64.whl (12.8 MB)

   -------------

In [2]:
pip install numpy requests

  Using cached requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
  Using cached charset_normalizer-3.4.3-cp312-cp312-win_amd64.whl.metadata (37 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
Using cached requests-2.32.4-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.3-cp312-cp312-win_amd64.whl (107 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Using cached certifi-2025.8.3-py3-none-any.whl (161 kB)

   -------- ------------------------------- 1/5 [idna]
   ---------------------------------------- 5/5 [requests]

Note: you may need to restart the kernel to use updated packages.


In [3]:
data = """
Making an Impact
Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world."""

In [4]:
clean_data = data.strip()

In [5]:
clean_data

"Making an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world."

In [10]:
max_char = 250
overlap = 50
chunks = []
i = 0
while i < len(clean_data):
    chunk = clean_data[i:i+max_char]
    chunks.append(chunk)
    i = i+max_char-overlap

In [11]:
len(chunks),chunks

(4,
 ["Making an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing",
  "1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opp",
  'backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused o',
  'ignificant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.'])

In [9]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-bd1c2c0040070482ae67810b5f11f07102ac766294607b7a1ba0373e4947f011"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [12]:
for i in chunks:
    embedding = generate_embeddings(i)
    print(embedding)
    

[ 0.01248232 -0.01566538  0.04053795 ... -0.00694485  0.00069712
  0.00524152]
[-0.02577963  0.00726159  0.04473717 ... -0.01537594 -0.01525787
 -0.00111679]
[-0.01770032 -0.03358822  0.01932273 ... -0.01813881  0.01174419
  0.02199751]
[-0.01897111 -0.02526139  0.02755397 ... -0.01662122 -0.00260423
  0.02576289]


In [13]:
emb_list = []
meta= []
for idx,chunk in enumerate(chunks):
    vec = generate_embeddings(chunk)
    emb_list.append(vec.astype("float32"))
    
    meta.append({"id": idx, "text": chunk})

In [14]:
xb = np.vstack(emb_list)

In [16]:
xb

array([[ 0.01248232, -0.01566538,  0.04053795, ..., -0.00694485,
         0.00069712,  0.00524152],
       [-0.02577963,  0.00726159,  0.04473717, ..., -0.01537594,
        -0.01525787, -0.00111679],
       [-0.0177019 , -0.03359122,  0.01935369, ..., -0.01815505,
         0.011716  ,  0.02199947],
       [-0.01897309, -0.02526402,  0.02752818, ..., -0.01665161,
        -0.00258659,  0.02573691]], shape=(4, 1536), dtype=float32)

In [15]:
import faiss

In [17]:
faiss.normalize_L2(xb)

In [18]:
xb

array([[ 0.01248232, -0.01566538,  0.04053795, ..., -0.00694485,
         0.00069712,  0.00524152],
       [-0.02577963,  0.00726159,  0.04473717, ..., -0.01537594,
        -0.01525787, -0.00111679],
       [-0.0177019 , -0.03359122,  0.01935369, ..., -0.01815505,
         0.011716  ,  0.02199947],
       [-0.01897309, -0.02526402,  0.02752818, ..., -0.01665161,
        -0.00258659,  0.02573691]], shape=(4, 1536), dtype=float32)

In [19]:
xb_normal = faiss.normalize_L2(xb)
xb_normal

In [20]:
xb_normal

In [21]:
index = faiss.IndexFlatIP(1536)
index.add(xb)

In [22]:
index_path = "index_sudhanshu.faiss"
meta_path = "meta_sudhanshu.jsonl"

In [23]:
faiss.write_index(index, index_path)

In [24]:
import json, os

In [25]:
with open(meta_path, "w") as f:
    for item in meta:
        f.write(json.dumps(item) + "\n")

In [27]:
query = "who is sudhanshu"
q = generate_embeddings(query).astype("float32").reshape(1, -1)
faiss.normalize_L2(q)
index.search(q, 2)

(array([[0.4030654 , 0.38279307]], dtype=float32), array([[3, 1]]))

In [30]:
from dotenv import load_dotenv
import os

load_dotenv()

True

In [31]:
from qdrant_client import QdrantClient

qdrant_client = QdrantClient(
    url="https://71db4fc0-98e9-40f8-89d4-6ab4b80be59a.us-east4-0.gcp.cloud.qdrant.io:6333", 
    api_key=os.getenv('Qdrant_api_key'),
)

print(qdrant_client.get_collections())

collections=[]


In [32]:
collection_name = 'first_test'

In [33]:
from qdrant_client import models
qdrant_client.recreate_collection(
    collection_name=collection_name,
    vectors_config=models.VectorParams(
        size=1536,distance=models.Distance.COSINE))

C:\Users\Digital Suppliers\AppData\Local\Temp\ipykernel_12068\908753693.py:2: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(


True

In [35]:
points = []

for idx, (chunk,emb) in enumerate(zip(chunks, xb)):
    points.append(
        models.PointStruct(
            id=idx,
            vector=emb.astype("float32").tolist(),
            payload={"text": chunk}
        )
    )

In [36]:
qdrant_client.upsert(collection_name=collection_name,points=points)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [38]:
query = "who is Sudhanshu"
query_emb = generate_embeddings(query)
query_vec = np.array(query_emb).astype("float32")

In [39]:
query_vec

array([-0.02782329, -0.03006021, -0.00879688, ..., -0.001219  ,
        0.01913951,  0.00206413], shape=(1536,), dtype=float32)

In [40]:
qdrant_client.search(collection_name=collection_name,query_vector=query_vec,limit=2,with_payload=True)

C:\Users\Digital Suppliers\AppData\Local\Temp\ipykernel_12068\1052391240.py:1: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  qdrant_client.search(collection_name=collection_name,query_vector=query_vec,limit=2,with_payload=True)


[ScoredPoint(id=3, version=0, score=0.41743177, payload={'text': 'ignificant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1, version=0, score=0.39950466, payload={'text': "1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opp"}, vector=None, shard_key=None, order_value=None)]